Hw2
artemgur/artemgur pull request #4
Opened 2020-09-20 17:40 UTC by artemgur

Added Github Action, done test coverage badge

2020-09-20 20:14 UTC, CoralineRed requested changes

2020-09-20 20:14 UTC, CoralineRed commented on Calculator/Calculator/Program.cs
>  		private static double ReadDouble() => double.Parse(Console.ReadLine());
Не проверяется ввод перед парсом.

2020-09-21 13:13 UTC, artemgur commented on Calculator/Calculator/Program.cs
>  		private static double ReadDouble() => double.Parse(Console.ReadLine());
Исправил в соответствии с замечаниями

2020-09-23 16:53 UTC, CoralineRed requested changes

2020-09-23 16:53 UTC, CoralineRed commented on Calculator/CalculatorTests/CalculatorTests.cs
> +		public static void TestSum(double a, double b) => Assert.AreEqual(a + b, Calculator.Calculator.Calculate(a, b, '+'));
Некорректные названия тестов.

2020-09-23 17:05 UTC, CoralineRed requested changes
В классе Calculator в методе Calculate не проверяется деление на ноль.

2020-09-24 13:04 UTC, CoralineRed approved these changes

2020-09-24 14:57 UTC, merged